// This file is auto-generated by tools/getServerlessFunctionTest.mjs 
// Fri Apr 07 2023 19:22:38 GMT+0100 (British Summer Time)
 export const authContext = `
const go = async () => {
  Lit.Actions.setResponse({response: JSON.stringify({"Lit.Auth": Lit.Auth})})
};

go();
`;