// This file is auto-generated by tools/getServerlessFunctionTest.mjs 
// Tue Nov 01 2022 21:09:39 GMT+0000 (Greenwich Mean Time)
 export const authContext = `
const go = async () => {
  Lit.Actions.setResponse({response: JSON.stringify({"Lit.Auth": Lit.Auth})})
};

go();
`;