// This file is auto-generated by tools/getServerlessFunctionTest.mjs 
// Tue Nov 01 2022 20:48:24 GMT+0000 (Greenwich Mean Time)
 export const decrypt = `
const go = async () => {  
  // this requests a decryption share from the Lit Node
  // the decryption share will be automatically returned in the HTTP response from the node
  const decryptionShare = await LitActions.decryptBls({ toDecrypt, publicKey, decryptionName });
};

go();
`;