// This file is auto-generated by tools/getServerlessFunctionTest.mjs 
// Mon Oct 31 2022 15:31:51 GMT+0000 (Greenwich Mean Time)
 export const encodingTest = `
const go = async () => {  
  // this requests a signature share from the Lit Node
  // the signature share will be automatically returned in the HTTP response from the node
  // all the params (toSign, publicKey, sigName) are passed in from the LitJsSdk.executeJs() function
  const decodedData = LitActions.uint8arrayFromString(toSign, 'base64');
  console.log('decodedData', decodedData);
  const sigShare = await LitActions.signEcdsa({ toSign: decodedData, publicKey , sigName });
};

go();
`;