// This file is auto-generated by tools/getServerlessFunctionTest.mjs 
// Fri Apr 07 2023 19:22:38 GMT+0100 (British Summer Time)
 export const encodingTest = `
const go = async () => {  
  // this requests a signature share from the Lit Node
  // the signature share will be automatically returned in the HTTP response from the node
  // all the params (toSign, publicKey, sigName) are passed in from the LitJsSdk.executeJs() function
  const decodedData = LitActions.uint8arrayFromString(toSign, 'base64');
  console.log('decodedData', decodedData);
  const sigShare = await LitActions.signEcdsa({ toSign: decodedData, publicKey , sigName });
};

go();
`;