// This file is auto-generated by tools/getServerlessFunctionTest.mjs 
// Fri Jul 05 2024 13:38:02 GMT+0100 (British Summer Time)
 export const ethers = `
const go = async () => {
  const val = ethers.utils.formatEther(10000)
  LitActions.setResponse({response: JSON.stringify({val})})
};

go();
`;