// This file is auto-generated by tools/getServerlessFunctionTest.mjs 
// Tue Nov 01 2022 20:48:24 GMT+0000 (Greenwich Mean Time)
 export const ethers = `
const go = async () => {
  const val = ethers.utils.formatEther(10000)
  LitActions.setResponse({response: JSON.stringify({val})})
};

go();
`;