// This file is auto-generated by tools/getServerlessFunctionTest.mjs 
// Tue Nov 01 2022 21:09:39 GMT+0000 (Greenwich Mean Time)
 export const helloworld = `
const go = async () => {
  // this requests a signature share from the Lit Node
  // the signature share will be automatically returned in the response from the node
  // and combined into a full signature by the LitJsSdk for you to use on the client
  // all the params (toSign, publicKey, sigName) are passed in from the LitJsSdk.executeJs() function
  const sigShare = await LitActions.signEcdsa({ toSign, publicKey, sigName });
};

go();
`;