// This file is auto-generated by tools/getServerlessFunctionTest.mjs 
// Tue Nov 01 2022 21:09:39 GMT+0000 (Greenwich Mean Time)
 export const multipleSigs = `
const go = async () => {  
  // this requests a signature share from the Lit Node
  // the signature share will be automatically returned in the HTTP response from the node
  // all the params (toSign, publicKey, sigName) are passed in from the LitJsSdk.executeJs() function
  const sigShare1 = await LitActions.signEcdsa({ toSign: [65, 65, 65], publicKey: "1", sigName: "sig1" });
  const sigShare2 = await LitActions.signEcdsa({ toSign: [66, 66, 66], publicKey: "1", sigName: "sig2" });
};

go();
`;